---
title: "HW5"
author: "Gaby Ramirez"
date: "2022-11-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(stringr)
library(readr)
library(lubridate)
library(dygraphs)
library(ggplot2)
```

# Loading the data and 
```{r}
list.files("../data")

getwd()
setwd("C:/Users/gabyrm/Desktop/HW5-Rclass/data")
homicides <- read.csv("C:/Users/gabyrm/Desktop/HW5-Rclass/data/homicide-data.csv")
```

# Separate by ymd and name summer vs winter months 

```{r warning=FALSE}
homicides_MD <- homicides %>% 
  filter(city == "Baltimore") %>% 
  mutate(date = ymd(reported_date),
         year = year(date),
         month = month(date)) %>% 
  group_by(month, year) %>% 
  count() %>% 
  unite("date", year:month, remove = FALSE) %>% 
  mutate(winter_months = month %in% c(11, 12, 1:4)) %>% 
  rename(Winter = winter_months) %>% 
  mutate(summer_months = month %in% c(5:10)) %>% 
  rename(Summer = summer_months)
```


```{r}
freddie <- homicides %>% 
  filter(victim_last == "GREY") %>% 
  filter(disposition == "Closed by arrest") %>% 
  mutate(date = ymd(reported_date),
         year = year(date),
         month = month(date)) %>% 
  group_by(month, year) %>% 
  count() %>% 
  unite("date", year:month, remove = FALSE) %>% 
   mutate(winter_months = month %in% c(11, 12, 1:4)) %>% 
  rename(Winter = winter_months) %>% 
  mutate(summer_months = month %in% c(5:10)) %>% 
  rename(Summer = summer_months)
```


```{r plot fig.height=7, fig.width=15}
MD_graph <- homicides_MD %>% 
  ggplot(aes(x = date, y = n)) +
  geom_col(aes(fill = Winter)) +
  geom_vline(xintercept = freddie$date, color = "red", linetype = "longdash", size = 2) +
  annotate("text", x = freddie$date, y = 40, label="Arrest of\n Freddie Gray", hjust = 1.1, size = 8, color = "white") +
  geom_smooth(span = 0.1, color = "blue", se = FALSE, size = 1) +
  labs(x = "Date",
       y = "Monthly homicides") +
  ggtitle("Homicides in Baltimore, MD") +
  theme_dark() + 
  theme(legend.position = "bottom") +
  scale_fill_manual(values = c("gray", "sky blue"), name = " ", labels = c("Summer", "Winter"))
plot(MD_graph)
```



